import math, txt_reader


def wrap_string_in_html(program, source_file):
    from webbrowser import open_new_tab

    filename = program + '.html'
    f = open(filename,'w')

    wrapper = """<html>
    <head>
        <title>%s output</title>
        <style>
            h2 {
                text-align: center;
            }
            body {
                font-family: Georgia;
                word-wrap: break-word;
            }            
            #poem {
                background-color: white;
            }
            .container {
                width: 80%s;
                height: 200px;
                margin: auto;
                padding: 10px;
            }
            .blackout-float {
                width: 500px;
                padding: 10px 10px 10px 10px;
                background-color: black;
                color: black;
                float: right;
            }
            .haiku-float {
                width: 300px;
                padding: 10px 10px 10px 10px;
                font-size: 20px;
                float: left
            }
        </style>
    </head>
        <body>  
            <section class="container">
                <h2>
                    Poem Generated By 
                    <a href=\"https://github.com/kabramow/roboetry\">Roboetry</a> 
                </h2>
                <h2>
                    from %s
                </h2>
                <div class=\"haiku-float\"><p>%s</p></div>
                <div class=\"blackout-float\"><p>%s</p></div>
                
            </section>
            
        </body>
    </html>"""

    text = txt_reader.get_random_selection(source_file)
    poem_words = txt_reader.get_up_to_20_random_words(text)
    title = txt_reader.get_title(source_file)

    whole = wrapper % (program,"%", title, poem_generator(poem_words), body_generator(poem_words, text))
    f.write(whole)
    f.close()

    open_new_tab(filename)
    #return whole


def body_generator(poem_words, text):
    text_words = text.split(" ")
    print(text_words)
    out_text = ""
    for word in text_words:
        if len(poem_words) != 0:
            if word == poem_words[0]:
                print("here")
                poem_words = poem_words[1:]
                out_text += "<span id=\"poem\">" + word + "</span>" + " "
            elif word == "\n":
                out_text += "<br>"
            else:
                out_text += word + " "
        elif word == "\n":
            out_text += "<br>"
        else:
            out_text += word + " "

    return out_text


def poem_generator(poem_words):
    words_per_line = math.trunc(len(poem_words) / 3)
    first_line = poem_words[0:words_per_line]
    middle_line = poem_words[words_per_line:(-1*words_per_line)]
    last_line = poem_words[(-1*words_per_line):]
    retString = ""
    for word in first_line:
        retString += word + " "
    retString += "\n</p><p>\n"
    for word in middle_line:
        retString += word + " "
    retString += "\n</p><p>\n"
    for word in last_line:
        retString += word + " "
    return retString

